version: '3.8'

services:
  web:
    build: .
    container_name: elektron_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=elektron

  db:
    image: mysql:8.0
    container_name: elektron_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elektron
    volumes:
      - db_data:/var/lib/mysql
      - ./elektron.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  db_data: